### PR TITLE
flow6979 - Count Ones in a 2D Array

### PR DESCRIPTION
**Pull request by flow6979**

### CODE REVIEW

**Comment by dasundev** [comment]
Hey, Thanks for the PR! 

Unfortunately, this is not correct you must follow contribution guidelines. please create a new file with your username inside "c++" folder and solve all problems within one file. when you are solving each problem, please open PR one by one for the same file.

I'm closing this PR.

**Comment by flow6979** [comment]
Hey, @dasundev it would be great if you talk to me on discord or some other platform. 
thank you

**Comment by dasundev** [comment]
Just follow the contribution guidelines. You can follow this [PR](https://github.com/dasundev/hacktoberfest-2022/pull/28) as well

**Comment by flow6979** [comment]
so basically you are saying- 
1. create a CPP file with my username
2. add code of every problem and if any problem is done then open the pr for that code in the same file
3. separate all the code of different problems by a comment containing the name of the problem

what I am getting in my mind is that I should create a c++ function for individual problems in the same file. example-

int countNumberOfOnes(){
         // code
}
void capialization(){
        // code
}
int main(){
    //function calling
}

and every time I add a function for a new problem I open a PR.

am I going in the right direction?

**Comment by dasundev** [comment]
@flow6979 You are correct!

**Pull request closed without merging**
